# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import compute_pb2 as compute__pb2


class ComputeStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SayHello = channel.unary_unary(
        '/compute.Compute/SayHello',
        request_serializer=compute__pb2.HelloRequest.SerializeToString,
        response_deserializer=compute__pb2.HelloReply.FromString,
        )


class ComputeServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SayHello(self, request, context):
    """Compute是rpc服务的名字
    后面 服务端 会用到 <ComputeServicer>，客户端 会用到 <ComputeStub>
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ComputeServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SayHello': grpc.unary_unary_rpc_method_handler(
          servicer.SayHello,
          request_deserializer=compute__pb2.HelloRequest.FromString,
          response_serializer=compute__pb2.HelloReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'compute.Compute', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
